### ISSUE TITLE
Enforced attribute: Instance Scheduler wrong behaviour

### ISSUE THREAD

**Issue by v-greco** [aws-solutions/aws-instance-scheduler#379] opened 2023-02-27 09:35 UTC
Hello,

I installed the instance scheduler stack for the customer and I'm facing issue using the "enforced" attribute. If I switch it from true to false the scheduler continues to behave as the value remaing true so, for example, it continues to shutdown the instances when the customer turn them on .

Even if I changed "enforced" to “false”, the scheduler continued to act as it has the previous value (“true”). Following part of  the cloudtrail log:

•	February 21, 2023, 21:30:57 (UTC+01:00) the scheduler stopped the instance (and the “enforced” value was false so it shouldn’t have stopped the instance again until the scheduled time)
•	February 21, 2023, 21:36:25 (UTC+01:00) the customer turned on the instance i-09XXXXXXXdce492 
•	February 21, 2023, 21:40:56 (UTC+01:00) the scheduler stopped again the instance --> this is the wrong behavior since the “enforced” parameter value was “false”.

I share also the schedule/period configuration:

-------------------------SCHEDULE-------------------------------
{
  "type": {
    "S": "schedule"
  },
  "name": {
    "S": "server-lun-ven-h8m00-h19m00"
  },
  "description": {
    "S": "EC2 lun-ven  8:00-19:00"
  },
  "periods": {
    "SS": [
      "lun-ven-8-00-19-00",
      "shutdown-weekend-19-00"
    ]
  },
  "timezone": {
    "S": "Europe/Rome"
  },
 "enforced": {
        "S": "false"
    }
}
}

-----------------------END SCHEDULE---------------------------
-------------------------PERIODS-------------------------------
{
  "type": {
    "S": "period"
  },
  "name": {
    "S": "lun-ven-8-00-19-00"
  },
  "begintime": {
    "S": "08:00"
  },
  "description": {
    "S": "server-lun-ven-h0m00-h19m00"
  },
  "endtime": {
    "S": "19:00"
  },
  "weekdays": {
    "SS": [
      "mon-fri"
    ]
  }
}

----------------------------------------------------------------------

{
  "type": {
    "S": "period"
  },
  "name": {
    "S": "shutdown-weekend-19-00"
  },
  "description": {
    "S": "shutdown-weekend-19-00"
  },
  "endtime": {
    "S": "19:00"
  },
  "weekdays": {
    "SS": [
      "sat-sun"
    ]
  }
}

-------------------------END PERIODS-------------------------------

I need the scheduler take the new values of parameters almost immediately without the need to "reboot" it.

I whish you a great day,

Vincenzo.

**Comment by CrypticCabub** [comment] 2023-02-27 14:36
@v-greco Thanks for reaching out!

I have been unable to reproduce the behavior you mentioned. Instance Scheduler reloads the schedule configuration on every iteration so it should pick up any changes you make immediately.

Could you please update the Instance Scheduler stack and set the "Enable CloudWatch Logs" setting to "Yes", recreate the behavior, and then send me the debug logs printed in CloudWatch for the problem instance?

**Comment by v-greco** [comment] 2023-02-28 15:02
Hello CrypticCabub,

thanks for your availability, to be honest I noticed I don't have the last versione of the Instance Scheduler available. The installed one is v1.4.1 while the last available is the 1.4.2, comparing the code I noticed an additional permission on dynamodb. Let's try it.

Regards,

Vincenzo.

**Comment by CrypticCabub** [comment] 2023-03-08 20:49
marking as closed. Please re-open if you continue having trouble

**Closed by CrypticCabub** 2023-03-08 20:49 UTC
