### ISSUE TITLE
Schedule Name is Unknown on starttime trigger

### ISSUE THREAD

**Issue by AMMullan** [aws-solutions/aws-instance-scheduler#310] opened 2022-05-05 10:09 UTC
We're using v1.4.0 and are having an issue where instances are getting stopped fine when the period' endtime condition is met, but the instances are not starting when the begintime condition is met.

period:
`{
  "type": {
    "S": "period"
  },
  "name": {
    "S": "office-hours"
  },
  "begintime": {
    "S": "11:00"
  },
  "description": {
    "S": "Office hours"
  },
  "endtime": {
    "S": "11:05"
  },
  "weekdays": {
    "SS": [
      "mon-fri"
    ]
  }
}`

schedule:
`{
  "type": {
    "S": "schedule"
  },
  "name": {
    "S": "uk-office-hours"
  },
  "description": {
    "S": "Office hours in UK"
  },
  "periods": {
    "SS": [
      "office-hours"
    ]
  },
  "timezone": {
    "S": "Europe/London"
  }
}`

We have the **Schedule = uk-office-hours** tag assigned to an instance and the instance starts, but when the time condition is met for the stop, we see the following in CloudWatch Logs:

_WARNING : Skipping instance EC2:i-XXX in region eu-west-1 for account XXX, schedule name "uk-office-hours" is unknown_ (instance/account details redacted)

From what I understand we've not got anything misconfigured so wondering if this is a bug?

**Comment by praveenis** [comment] 2022-05-18 16:19
@AMMullan We are not able to reproduce this issue with same period and schedule in v1.4.0 /v1.4.1 , the scheduling is working fine as expected. Can you please confirm if other schedules are working in the account/region.

**Comment by AMMullan** [comment] 2022-05-21 16:46
@praveenis this was setup in a sandbox account and this was the only schedule created. I might try tearing it down and using the newer version and starting from scratch. I'll reply to this if I can still replicate.

**Comment by morjoan** [comment] 2022-09-20 18:47
@AMMullan closing this ticket. Please reopen if this is still an issue.

**Closed by morjoan** 2022-09-20 18:47 UTC
